// johnverrone/src/lib/components/YouTubeVideo.svelte
<script lang="ts">
	export let title: string;
	export let videoId: string;
</script>

<div class="wrapper">
	<h3>{title}</h3>
	<iframe
		src={`https://www.youtube.com/embed/${videoId}`}
		title="YouTube video player"
		frameBorder="0"
		allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
		allowFullScreen
	></iframe>
</div>

<style>
	.wrapper {
		text-align: center;
	}

	h3 {
		font-family: var(--font-family-heading);
		margin-bottom: 12px;
	}

	iframe {
		width: min(100%, 800px);
		height: 100%;
		aspect-ratio: 16/9;
	}
</style>

// johnverrone/components/YouTubeVideo/YouTubeVideo.tsx
import styled from '@emotion/styled';

const Wrapper = styled.div`
  text-align: center;
`;

const VideoTitle = styled.h3`
  font-family: var(--font-family-heading);
  text-align: center;
  margin-bottom: 12px;
`;

const IFrame = styled.iframe`
  width: min(100%, 800px);
  height: 100%;
  aspect-ratio: 16/9;
`;

interface YouTubeVideoProps {
  videoId: string;
  title: string;
}

export const YouTubeVideo = ({ videoId, title }: YouTubeVideoProps) => (
  <Wrapper>
    <VideoTitle>{title}</VideoTitle>
    <IFrame
      src={`https://www.youtube.com/embed/${videoId}`}
      title="YouTube video player"
      frameBorder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowFullScreen
    ></IFrame>
  </Wrapper>
);
